### ISSUE TITLE
'onComplete' event not firing for Safari on iOS

### ISSUE THREAD

**Issue by mangione77** [cozylife/audio-fingerprint#1]
Hello Rick, thanks for your code, I've been using it with a great degree of success. However, I found a small problem on iOS devices, the onComplete handler doesn't get fired as the audioContext does not appear to stop - is this a known Safari or is there any workaround?

Thanks in advance

**Comment by rickmacgillis** [comment]
@mangione77 - This repo is discontinued, as it got added to the [FingerprintJS2 project](https://github.com/Valve/fingerprintjs2).

I recommend using FingerprintJS2 as it's still well maintained.
